title: "Sreekar Trail Portfolio"
description: "Trail running adventures, races, and stories"
baseurl: ""
url: "https://yourusername.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "Sreekar"
